###GetAll
POST http://localhost:9999/banners.getAll/ HTTP/1.1

### save
POST http://localhost:9999/banners.save/?id=0&title=депозиты с доходом 60/40&content=Вкладывайте в национальной валюте&button=рассчитать доход&link=https://alif.tj/deposit#CountYourIncome HTTP/1.1

### update

POST http://localhost:9999/banners.save/?id=1&title=депозиты&content=Вкладывайте в национальной валюте&button=рассчитать доход&link=https://alif.tj/deposit#CountYourIncome HTTP/1.1


###  find
POST http://localhost:9999/banners.getById/?id=1

### delete
POST http://localhost:9999/banners.removeById/?id=5
